general.import = [
  "~/.config/cachydae/current/theme/alacritty.toml",
  "~/.config/cachydae/current/font/alacritty.toml",
]

[env]
TERM = "xterm-256color"

[font]
size = 9

[window]
padding.x = 14
padding.y = 14
decorations = "None"

[keyboard]
bindings = [
  { key = "Insert", mods = "Shift", action = "Paste" },
  { key = "Insert", mods = "Control", action = "Copy" },
]
